# Generated by Django 3.2.5 on 2021-11-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField()),
                ('gender', models.TextField()),
                ('situation', models.TextField()),
                ('emotion', models.TextField()),
                ('sentence', models.TextField()),
            ],
            options={
                'db_table': 'diary_dataset',
            },
        ),
    ]
